name: Telegram Auto Post Server

on:
  push:
    branches: [ main ]
  schedule:
    # Her 5 minutdan GitHub serweri özi açylyp bodiň ýagdaýyny barlap durar
    - cron: '*/5 * * * *'
  workflow_dispatch: # El bilen hem göni işletmek üçin

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kody barlamak
        uses: actions/checkout@v3

      - name: Python gurnamak
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # EDIL TERMUX-DAKY PKG INSTALL ÝALY KITAPHANALARY GURNAÝAN BUÝRUK:
      - name: Gerekli Gurallary Gurnamak
        run: pip install pyTelegramBotAPI requests

      # BOTY ASYL IŞE GIRIZÝÄN BUÝRUK:
      - name: Boty Arka Planda Işletmek
        run: |
          python bot.py &
          sleep 30
          
